"""add walls and wall_holds

Revision ID: 1a40420a1987
Revises: 3164bfd22299
Create Date: 2026-03-16 20:17:11.283843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a40420a1987'
down_revision: Union[str, None] = '3164bfd22299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_upload_id', sa.UUID(), nullable=True),
    sa.Column('latest_job_id', sa.UUID(), nullable=True),
    sa.Column('original_image_uri', sa.Text(), nullable=False),
    sa.Column('preview_image_uri', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['latest_job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['original_upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wall_holds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wall_id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('class_name', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('x2', sa.Float(), nullable=False),
    sa.Column('y2', sa.Float(), nullable=False),
    sa.Column('center_x', sa.Float(), nullable=False),
    sa.Column('center_y', sa.Float(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('label_text', sa.String(length=255), nullable=True),
    sa.Column('label_x', sa.Float(), nullable=True),
    sa.Column('label_y', sa.Float(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_user_adjusted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['wall_id'], ['walls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wall_holds')
    op.drop_table('walls')
    # ### end Alembic commands ###
