"""initial schema

Revision ID: 3164bfd22299
Revises: 
Create Date: 2026-03-01 19:50:00.855982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3164bfd22299'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=60), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_datasets_name_version')
    )
    op.create_index('ix_datasets_name', 'datasets', ['name'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_uri', sa.Text(), nullable=False),
    sa.Column('original_sha256', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uploads_created_at', 'uploads', ['created_at'], unique=False)
    op.create_table('training_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('code_version', sa.String(length=80), nullable=True),
    sa.Column('hyperparams', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_runs_created_at', 'training_runs', ['created_at'], unique=False)
    op.create_index('ix_training_runs_status', 'training_runs', ['status'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('training_run_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('weights', 'plot', 'metrics', 'other', name='artifacttype'), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifacts_training_run_id', 'artifacts', ['training_run_id'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=60), nullable=False),
    sa.Column('task', sa.String(length=30), nullable=False),
    sa.Column('weights_uri', sa.Text(), nullable=False),
    sa.Column('training_run_id', sa.UUID(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_models_name_version')
    )
    op.create_index('ix_models_created_at', 'models', ['created_at'], unique=False)
    op.create_index('ix_models_name', 'models', ['name'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='jobstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('result_annotated_uri', sa.Text(), nullable=True),
    sa.Column('inference_meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_status_created_at', 'jobs', ['status', 'created_at'], unique=False)
    op.create_index('ix_jobs_upload_id', 'jobs', ['upload_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('class_name', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('x2', sa.Float(), nullable=False),
    sa.Column('y2', sa.Float(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_job_id', 'predictions', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_predictions_job_id', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_jobs_upload_id', table_name='jobs')
    op.drop_index('ix_jobs_status_created_at', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_models_name', table_name='models')
    op.drop_index('ix_models_created_at', table_name='models')
    op.drop_table('models')
    op.drop_index('ix_artifacts_training_run_id', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_training_runs_status', table_name='training_runs')
    op.drop_index('ix_training_runs_created_at', table_name='training_runs')
    op.drop_table('training_runs')
    op.drop_index('ix_uploads_created_at', table_name='uploads')
    op.drop_table('uploads')
    op.drop_index('ix_datasets_name', table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
