"""add_route_domain_model

Revision ID: 9e63c73e8b8b
Revises: 1a40420a1987
Create Date: 2026-03-23 20:08:44.096241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e63c73e8b8b'
down_revision: Union[str, None] = '1a40420a1987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wall_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wall_id'], ['walls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_routes_wall_id', 'routes', ['wall_id'], unique=False)
    op.create_table('route_holds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('wall_hold_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['wall_hold_id'], ['wall_holds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'wall_hold_id', name='uq_route_holds_route_wall_hold')
    )
    op.create_index('ix_route_holds_route_id', 'route_holds', ['route_id'], unique=False)
    op.create_index('ix_route_holds_wall_hold_id', 'route_holds', ['wall_hold_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_route_holds_wall_hold_id', table_name='route_holds')
    op.drop_index('ix_route_holds_route_id', table_name='route_holds')
    op.drop_table('route_holds')
    op.drop_index('ix_routes_wall_id', table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
