"""Add User, RefreshToken, and ownership fields

Revision ID: b070e9f88974
Revises: 9e63c73e8b8b
Create Date: 2026-04-12 12:44:17.003076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b070e9f88974'
down_revision: Union[str, None] = '9e63c73e8b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by_token_id', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_token_id'], ['refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_tokens_family', 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_refresh_tokens_user_expires', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.add_column('routes', sa.Column('owner_user_id', sa.UUID(), nullable=True))
    op.add_column('routes', sa.Column('visibility', sa.String(length=50), server_default='private', nullable=False))
    op.add_column('routes', sa.Column('share_slug', sa.String(length=255), nullable=True))
    op.add_column('routes', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('routes', sa.Column('integrity_status', sa.String(length=50), server_default='valid', nullable=False))
    op.create_index('ix_routes_owner_updated', 'routes', ['owner_user_id', 'updated_at'], unique=False)
    op.create_unique_constraint(None, 'routes', ['share_slug'])
    op.create_foreign_key(None, 'routes', 'users', ['owner_user_id'], ['id'])
    op.add_column('walls', sa.Column('owner_user_id', sa.UUID(), nullable=True))
    op.add_column('walls', sa.Column('visibility', sa.String(length=50), server_default='private', nullable=False))
    op.add_column('walls', sa.Column('share_slug', sa.String(length=255), nullable=True))
    op.add_column('walls', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.create_index('ix_walls_owner_updated', 'walls', ['owner_user_id', 'updated_at'], unique=False)
    op.create_unique_constraint(None, 'walls', ['share_slug'])
    op.create_foreign_key(None, 'walls', 'users', ['owner_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'walls', type_='foreignkey')
    op.drop_constraint(None, 'walls', type_='unique')
    op.drop_index('ix_walls_owner_updated', table_name='walls')
    op.drop_column('walls', 'is_archived')
    op.drop_column('walls', 'share_slug')
    op.drop_column('walls', 'visibility')
    op.drop_column('walls', 'owner_user_id')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_constraint(None, 'routes', type_='unique')
    op.drop_index('ix_routes_owner_updated', table_name='routes')
    op.drop_column('routes', 'integrity_status')
    op.drop_column('routes', 'is_archived')
    op.drop_column('routes', 'share_slug')
    op.drop_column('routes', 'visibility')
    op.drop_column('routes', 'owner_user_id')
    op.drop_index('ix_refresh_tokens_user_expires', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_family', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
